### ISSUE TITLE
[next-sw] Status and Roadmap

### ISSUE THREAD

**Issue by KPixel** [DuCanhGH/next-pwa#100]
Hi, I will soon need to add PWA to my React app, but considering that [Workbox is half-abandonned](https://github.com/DuCanhGH/next-pwa/issues/77), I don't want to take dependencies on it. So, I am considering using next-sw...

Can you give a summary of what state it is in currently and what your vision for it is?

I am interested in helping next-sw be production-ready for precaching and runtime caching.

**Comment by DuCanhGH** [comment]
There are still many missing features and I'm not sure if those added already behave as expected (haven't really thoroughly tested them). I haven't been working on it for quite a few months now due to `next-pwa` itself (there are some opened issues that describe really weird bugs and I can't find out why they would happen - can't reproduce myself either) and other stuff outside of this project as well (have been really busy again recently tbh). So I'm sorry but I can't really give you a roadmap for `next-sw`, but I hope maybe it will be ready before 2023 ends :) I'd like to avoid Workbox for now as well, so there's no plan to abandon the project as a whole.

> I am interested in helping next-sw be production-ready for precaching and runtime caching.

You are welcome to open PRs! I'd be very grateful if you can :)

**Comment by KPixel** [comment]
OK. I will get started on it then.

By the way, for the long term success of this project, I would suggest creating a new repo. Since this one is a fork, [it is not visible when using GitHub Search](https://github.com/search?q=DuCanhGH+%22next-pwa%22&type=repositories).

**Comment by DuCanhGH** [comment]
@KPixel eh, I don't really care too much about how successful the project is to be honest. Those who need it will come for it. Also, I'd like to honor those who have contributed to `next-pwa` in the spirit of open source (I mean we can keep the history even when we create a new repo, but still), and let people know that this is, at the end of the day, still just a fork, rather than an original work of mine.

**Comment by KPixel** [comment]
That's ok. I meant "popular" in terms of letting people find this project more easily to help them.
Anyway, we can revisit that later.

**Comment by maiconcarraro** [comment]
@DuCanhGH for `next-pwa` makes sense to keep the fork, but for `next-sw` it does seem a good idea to build a new community around it, win-win for everyone

**Comment by DuCanhGH** [comment]
@maiconcarraro that would be disintegrating `next-sw` from the monorepo. Perhaps I can look into mirroring `next-sw` from this repo, or vice versa, mirroring `next-pwa` from a new repo.

**Comment by davit-b** [comment]
I'm a newcomer to the whole "Github" and open-source world ya'll are more proficient in than me. 

My experience in finding `DuCanhGH/next-pwa` was pure luck. I couldn't find it through google searches, and I stumbled into literally by accident after combing through the issues in `shadowwalker/next-pwa`.

So it was kinda dumb luck I found it. 

AFAIK, other people like me who google for "next pwa" stumble into that shadowwalker repo and go "ah fuck...it hasn't been maintained in 2 years and there is no alternative". 

For the world of PWAs and their development, that's kind of a tragedy.

**Comment by DuCanhGH** [comment]
@davit-b I mean if you only use Pages Router `next-pwa` should work just fine for now (it is just a development dependency after all and the whole bundling thing is Workbox's, which hasn't changed at all since then). Otherwise, Workbox just kinda slaps you with `bad-precaching-response`, which leads you to an issue in `shadowwalker/next-pwa` (if you do look into the cause), which then leads you here 💀 Oh and also there's an issue with this title: `Search for an active next-pwa fork` in that repo as well.

Kinda annoying that you can only search for forks with `fork:true` though.

**Comment by KPixel** [comment]
I've been looking into next-sw, and there is a lot more work to do left than I expected. And I didn't even consider many other scenarios handled currently by next-pwa + Workbox. I am concerned that next-sw will feel like a downgrade for people who were using next-pwa.

So, I wonder: Workbox is MIT-licensed. Would it be interesting to fork the parts that are perfectly fine in Workbox, and modernize the rest? Specifically, the Service Worker implementation in Workbox seems well designed and extensible: The main packages would be: [workbox-core](https://github.com/GoogleChrome/workbox/tree/v7/packages/workbox-core), [workbox-precaching](https://github.com/GoogleChrome/workbox/tree/v7/packages/workbox-precaching), [workbox-routing](https://github.com/GoogleChrome/workbox/tree/v7/packages/workbox-routing) and [workbox-strategies](https://github.com/GoogleChrome/workbox/tree/v7/packages/workbox-strategies). The registration in [workbox-window](https://github.com/GoogleChrome/workbox/tree/v7/packages/workbox-window) is also fine.

The part that would benefit from being rewritten is mainly the Webpack plugin.

**Comment by DuCanhGH** [comment]
@KPixel if that's the case then we will change the name of the package (and the description of this repo) since it isn't really what I was aiming for (I was trying to implement something that works just fine rather than reimplementing Workbox tbh). Also, if we were to go ahead with this then let me do the whole porting over the weekend (I want to modernize Workbox a bit after all). I think we should introduce Workbox's packages into our repo as new monorepo packages (and perhaps publish them too?).

**Comment by KPixel** [comment]
To go back to my initial question: What is your vision for next-sw?

I assumed that you wanted to build something that would, one day, replace next-pwa.

**Comment by DuCanhGH** [comment]
@KPixel I wanted to create something that is independent from Workbox yet simple enough that it doesn't become an unmaintainable one-size-fits-all monolith. Basically, removes configuration options that don't prove to be popular and necessary, and remove options that are duplicates of our existing options (for example, `browserslist` and `workboxOptions.babelPresetEnvTargets` are identical in `next-pwa`). Hmm, seems that straight up forking Workbox then modifying it to suit our usage still meets these criterias (although we will have to see whether we can remove certain features), so yeah.

**Comment by DuCanhGH** [comment]
@KPixel I've created a branch, see https://github.com/DuCanhGH/next-pwa/tree/workbox-fork. I picked the name Serwiss for the fork because I think it really kinda trips off the tongue. I will probably start work tomorrow, when my schedule finally gets a bit more vacant.

Feel free to open PRs into the fork (maybe from next week because there will be a lot of cleaning this week, but you can help clean the fork too!), or provide opinions where necessary :) I will appreciate that a lot! I've also opened [a Github project](https://github.com/users/DuCanhGH/projects/2/views/1).

So I think the final plan should be to create a Workbox fork, then reimplement `next-pwa` with this fork and publish under a new name. I don't think I would pick `next-sw` this time, because we still abstract the low level ServiceWorker stuff from the package.

**Comment by KPixel** [comment]
You already have many good ideas in next-pwa and next-sw.
So, I look forward to your consolidation of all the best parts in this new project.

**Comment by DuCanhGH** [comment]
@KPixel oh yeah, I forgot one thing - we want to make it searchable, right? Perhaps we can create a new repo right now, move `next-sw` off this repo, then make it a normal repo (that only includes `next-pwa`) rather than a monorepo. This returns everything to its original state. I think we can move the docs to the new repo as well.

**Comment by KPixel** [comment]
For the name, I thought about "Nextbox", but it is also taken. Maybe "Nextjsbox" (not as smooth...)

"NextPWA" is also available...

**Comment by DuCanhGH** [comment]
@KPixel well we are forking the entirety of Workbox so something prefixed with Next won't do.

NextGen feels a bit cliché not gonna lie though 💀

I picked Serwist, which is much like Serwiss but isn't taken. Check out https://github.com/serwist/serwist :)

**Comment by KPixel** [comment]
Serwist is fine :)

I think we can close this issue now.

**Comment by DuCanhGH** [comment]
@KPixel I think we should talk a bit about the direction of Serwist. So basically, I'm contemplating removing GenerateSW altogether. It just feels like a liability for the codebase since it doesn't do much aside from converting `runtimeCaching` to this:
```
let handler;

switch (entry.handler) {
  case "CacheFirst":
    handler = CacheFirst;
    break;
  case "CacheOnly":
    handler = CacheOnly;
    break;
  case "NetworkFirst":
    handler = NetworkFirst;
    break;
  case "NetworkOnly":
    handler = NetworkOnly;
    break;
  case "StaleWhileRevalidate":
    handler = StaleWhileRevalidate;
    break;
  default: {
    const __exhaustive = entry.handler;
    throw new Error(`Unhandled: ${__exhaustive}`);
  }
}

new handler({
  cacheName: cacheName ?? undefined,
  networkTimeoutSeconds,
  fetchOptions,
  matchOptions,
  plugins: [
    ...(plugins ?? []),
    backgroundSync && new BackgroundSyncPlugin(backgroundSync.name, backgroundSync.options),
    broadcastUpdate &&
      new BroadcastUpdatePlugin({
        // @ts-expect-error weird...
        channelName: broadcastUpdate.channelName,
        ...broadcastUpdate.options,
      }),
    cacheableResponse && new CacheableResponsePlugin(cacheableResponse),
    expiration && new ExpirationPlugin(expiration),
    precacheFallback && new PrecacheFallbackPlugin(precacheFallback),
    rangeRequests ? new RangeRequestsPlugin() : undefined,
  ].filter(nonNullable),
});
```
(this isn't Workbox's original code but my inference of it)

This is too unnecessary. We have to implement a function that serializes `runtimeCaching` to something we can pass to `@rollup/plugin-replace` (or deal with `lodash/template`, but this doesn't change the argument much), and there's no way to make this serialization function foolproof (I tried and Serwist's bundle size was much larger than that of Workbox, and Workbox's serialization isn't foolproof either - it just fails when you do `async a() { return b; }` since it tries to convert that to `a: async a() { return b; }`). Instead, we can export helper functions that do all the crazy transformation stuff that GenerateSW used to do, and migrate everyone to InjectManifest. This seems to be the most logical solution. What do you think? Since we are starting with a clean slate, we can do basically any breaking change after all.

**Comment by KPixel** [comment]
I don't fully understand: What has changed (in this context) compared to how things work in next-pwa?

**Comment by DuCanhGH** [comment]
@KPixel well, in a word: I just want to ask if you think removing Serwist's GenerateSW and migrate Serwist's  `next-pwa` to InjectManifest is fine. Seems that this feature is too unnecessary and significantly burdens the codebase.

**Comment by KPixel** [comment]
Yes, I think it's fine to remove GenerateSW.

Like you said, it is better to start with a better/clean slate. It will have immediate benefits and it doesn't prevent adding more features in the future.

**Comment by DuCanhGH** [comment]
@KPixel I did remove GenerateSW, but [with a catch](https://github.com/serwist/serwist/blob/refactor-rename/packages/sw/src/index.ts). Essentially, I introduced a new function named `installSerwist`, which does exactly what GenerateSW used to do. Pretty interesting solution that doesn't require some crazy stringifying :D

**Comment by KPixel** [comment]
Congrats!

**Comment by DuCanhGH** [comment]
@KPixel oh, sorry to hear that. Get well soon!
