### ISSUE TITLE
[Bug - next-pwa]: Deployment with vercel 

### ISSUE THREAD

**Issue by MrMelon1232** [DuCanhGH/next-pwa#125]
### Provide environment information

I am currently using the 9.7.2 version and have the latest node version

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/DuCanhGH/next-pwa/issues/107

### To reproduce

Deploy the app using vercel with a custom service worker.

### Describe the bug

Hey again, I am not sure if its related, but with the modification of babel due to the custom service worker not being recognized when specifying it, deploying the app using vercel provides this error: 
![image](https://github.com/DuCanhGH/next-pwa/assets/59658359/86f03d8c-20b3-4118-b899-1bfd67daed52)

Installing babel by itself using npm install make the deployment work but the custom service worker we want to use is then not recognized. Not sure if this is expected behavior but I was hoping if you could help us with this or maybe the new repo provides a solution for this.

### Expected behavior

Expected behavior: to be able to deploy our application using vercel while also having the custom service worker being targeted and used.

**Comment by DuCanhGH** [comment]
That's just your average ESLint moment. We don't make use of Babel at all, so I'm not sure why you think this plugin is related. I don't even know why you'd use ESLint in a bundled file either...

**Comment by MrMelon1232** [comment]
I see, would you happen to know how to have the service worker registration working while deploying the app on vercel ? I thought the error would be related to babel but I guess I was wrong. This is the error we are getting: 
![image (1)](https://github.com/DuCanhGH/next-pwa/assets/59658359/090684a7-fd2d-4b61-a239-216713c13718)

As a result, this is what we see in dev mode: 
![image](https://github.com/DuCanhGH/next-pwa/assets/59658359/f621e9aa-a33b-4d9b-b7bb-93a5cc183251)

**Comment by DuCanhGH** [comment]
@MrMelon1232 you are precaching "/~offline" multiple times:
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/f330ee61-1625-439b-ac9c-0a6d503c8a2f)
Recheck your precache list. Looking at your source, I noticed this line: `t7.push({ url: "/~offline" })`, which was unnecessary because the provided precache list already has "/~offline": `{ revision: "dKSb-EVmPw8vg-p8-Zh0w", url: "/~offline" }`. One more thing, it is recommended that you provide a `revision` unless this revision is in the URL itself, which is not the case for "/~offline".

Next time, if your service worker has an issue, you can go to Developer Tools > Application > Service Workers to see why. Hope this helps!

**Comment by MrMelon1232** [comment]
It works thanks! Weird how the error does not come up locally. I'll be closing it now.
