### ISSUE TITLE
[Bug - next-pwa]: `typeof window` transpiled as `object` at build time

### ISSUE THREAD

**Issue by JoseVSeb** [DuCanhGH/next-pwa#156]
### Provide environment information

`next@15.0.0-canary.35`
`@ducanh2912/next-pwa@10.2.7`

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/JoseVSeb/next-pwa-build-issue-typeof-window.git

### To reproduce

1. use `typeof window` in custom worker.
2. run build.
3. check the transpiled custom worker js file.

### Describe the bug

`typeof window` is transpiled as `object` in service worker js.

### Expected behavior

`typeof window` should be transpiled to `undefined` in service worker js.

### Additional information (if relevant)

I'm using an external library in my custom worker (firebase to control authentication) with `typeof window` in its code. when the application is built, the service worker fails to execute because the library tries to use window object.

this is caused because next build is configured to transpile `typeof window` as `object` in client side, but it should be `undefined` in service worker.

**Comment by DuCanhGH** [comment]
@JoseVSeb this is because same as Workbox, we create a child compiler on Next.js's web compiler. As such, it is not really possible for us to change `WebpackOptionsNormalized.target` to `"webworker"` (this either doesn't have an impact on initiated plugins or have unexpected effects on them), and we have to inherit Next.js's webpack plugins, which may statically replace `typeof window` with `"object"`. I suppose that we should replicate `createChildCompiler`'s behaviour but with `target` changed. Not sure if that changes anything though. Perhaps I'll have to dive into Next.js's internals for a bit.

**Comment by JoseVSeb** [comment]
> seems that [Next.js does force SWC to not statically replace `typeof window` with `"object"`](https://github.com/vercel/next.js/blob/5346185d37de3de4a8cfc391d6b7191e45ab37da/packages/next/src/build/swc/options.ts#L478-L482). Not sure what's the cause, then. Ah, that seems to be for files in node_modules only, actually.

I'm currently overriding some internal packages of Firebase using pnpm workspace because of an unrelated bug in Firebase. So, if that weren't the case, I wouldn't be facing this issue then? (the issue is triggered from the internal package that I have overridden)

**Comment by DuCanhGH** [comment]
@JoseVSeb if the bug is related to `typeof window`, yes.
