### ISSUE TITLE
[Bug]: Image flickering issue on safari using next13.4.1 

### ISSUE THREAD

**Issue by claritise** [DuCanhGH/next-pwa#23]
### Provide environment information

This issue only happens on safari for mobile and ios. Not an issue on chrome. The popping happens with both <img> and <Image> when utilising ` priority={true}` or ` rel="preload"`.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://pllum-7d61s0k53-claritise.vercel.app

### To reproduce

It is very intermittent. On browser it only happens after the page has been closed and reopened or refreshed a few times. On ios the sure fire way is to simply install the pwa and then close it completely and re-open. When the app is first installed there is no flickering.

### Describe the bug

When you click between screens or use swipes to navigate, all the images will flicker.

### Expected behavior

No flickering.

**Comment by claritise** [comment]
Fixed it by changing the caching method to prefer caching.

**Comment by claritise** [comment]
Although this fixed it i feel like the flickering shouldn't be expected behaviour when using StaleWhileRevalidate on images with safari... re-opening for any discussion on this?

**Comment by claritise** [comment]
The behaviour doesn't happen on Chrome, could this just be differences between how browsers treat `StaleWhileRevalidate`?

**Comment by DuCanhGH** [comment]
@claritise I'm seeing a similar behaviour across 3 browsers, which are Chromium, Firefox and Safari, which is the page's flashing a bit on load, but no flicker happens when I navigate. I'm also not aware of a behavioural difference between browsers for `StaleWhileRevalidate`. 

But if setting images to `CacheFirst` works for you then perhaps you should keep it like that (I've added a new option, `extendDefaultRuntimeCaching`, to help extend the default `runtimeCaching` array in `next-pwa` 8.5.0 :) This means that you don't have to copy the whole `cache.ts` to your config). This is how you can do it:
```js
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  extendDefaultRuntimeCaching: true,
  workboxOptions: {
    runtimeCaching: [
      {
        urlPattern: /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i,
        handler: "CacheFirst",
        options: {
          cacheName: "static-image-assets",
          expiration: {
            maxEntries: 64,
            maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
          },
        },
      },
    ]
  }
});

module.exports = withPWA({
  // Next.js config
});
```
This will override the `static-images-asset` entry in the default `runtimeCaching` array.

I don't think setting images' cache handler to `CacheFirst` by default for this plugin is a good way to go, however, as there are images that shouldn't be served from cache only, such as profile pictures.

**Comment by claritise** [comment]
@DuCanhGH It's really weird that you are also seeing the flickering on chrome. I am using chrome on mac and when navigating through links or back buttons, there is no flickering at all when using that preview version. 

Thank you for adding that config feature, definitely going to use it. I am thinking of solving this by making a separate cache specifically for immutable static image assets like UI elements etc...
